### PR TITLE
React Router migration from 3.x to 4.x

### PR DESCRIPTION
**Pull request by AlithAnar**
#15 First commit. It renders and works good.

### CODE REVIEW

**Comment by AlithAnar** [comment]
I've fixed routing in Login and SignUp process and tested it with your api. I suggest not using window.location.reload(); in SPA.

**Comment by j1348** [comment]
Can you squash your commit and rebase on master?

> I suggest not using window.location.reload(); in SPA.

Right. 👍

**Comment by AlithAnar** [comment]
I'll do that at the end of this day.

**Comment by j1348** [comment]
@AlithAnar let me know if you encounter some trouble cause I rewrite master history.
I think you just need to squash and cherry-pick on top on it.

**Comment by AlithAnar** [comment]
Yep, now I have trouble with rebase, because when I updated and merged my master branch to upstream and then merged master to `feat/migrate-react-router-4` instead of rebasing it.

**Comment by j1348** [comment]
I squash and rebase your PR. 

LGTM. Except for a little rendering issue with the login form position.

**Comment by j1348** [comment]
Now your code is on master. thx

**Pull request closed without merging**
