### PR TITLE
react router 4

### PR DESCRIPTION
**Pull request by BrianCortes**
issue: #15 

Hey @j1348 please check this PR

### CODE REVIEW

**Comment by BrianCortes** [comment]
captura de pantalla 2017-10-14 a la s 11 18 15 am

**Comment by j1348** [comment]
Can you plz squash your commit?

**Comment by BrianCortes** [comment]
@j1348 Done 👍

**Comment by BrianCortes** [comment]
@j1348 Done 👍

**Comment by j1348** [comment]
`/login` user process failed now.

**Comment by j1348** [comment]
I am closing the PR in favour of #17 because of /login trouble

**Pull request closed without merging**
